-- MySQL Script generated by MySQL Workbench
-- 06/01/17 17:27:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pm
-- -----------------------------------------------------
-- Project Management System DB
DROP SCHEMA IF EXISTS `pm` ;

-- -----------------------------------------------------
-- Schema pm
--
-- Project Management System DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pm` DEFAULT CHARACTER SET utf8 ;
USE `pm` ;

-- -----------------------------------------------------
-- Table `pm`.`developers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm`.`developers` ;

CREATE TABLE IF NOT EXISTS `pm`.`developers` (
  `DEVELOPER_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `EXPERIENCE` INT NOT NULL,
  `SALARY` INT NULL,
  PRIMARY KEY (`DEVELOPER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm`.`skills` ;

CREATE TABLE IF NOT EXISTS `pm`.`skills` (
  `SKILL_ID` INT NOT NULL AUTO_INCREMENT,
  `SKILL_NAME` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`SKILL_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm`.`projects` ;

CREATE TABLE IF NOT EXISTS `pm`.`projects` (
  `PROJECT_ID` INT NOT NULL AUTO_INCREMENT,
  `PROJECT_NAME` VARCHAR(100) NOT NULL,
  `COST` INT NULL,
  PRIMARY KEY (`PROJECT_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm`.`companies` ;

CREATE TABLE IF NOT EXISTS `pm`.`companies` (
  `COMPANY_ID` INT NOT NULL AUTO_INCREMENT,
  `COMPANY_NAME` VARCHAR(100) NOT NULL,
  `COMPANY_ADDRESS` VARCHAR(100) NULL,
  PRIMARY KEY (`COMPANY_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm`.`customers` ;

CREATE TABLE IF NOT EXISTS `pm`.`customers` (
  `CUSTOMER_ID` INT NOT NULL AUTO_INCREMENT,
  `CUSTOMER_NAME` VARCHAR(100) NOT NULL,
  `CUSTOMER_ADDRESS` VARCHAR(100) NULL,
  PRIMARY KEY (`CUSTOMER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`developers_skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm`.`developers_skills` ;

CREATE TABLE IF NOT EXISTS `pm`.`developers_skills` (
  `DEVELOPER_ID` INT NOT NULL,
  `SKILL_ID` INT NOT NULL,
  PRIMARY KEY (`DEVELOPER_ID`, `SKILL_ID`),
  INDEX `fk_developers_has_skills_skills1_idx` (`SKILL_ID` ASC),
  INDEX `fk_developers_has_skills_developers_idx` (`DEVELOPER_ID` ASC),
  CONSTRAINT `fk_developers_has_skills_developers`
    FOREIGN KEY (`DEVELOPER_ID`)
    REFERENCES `pm`.`developers` (`DEVELOPER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_developers_has_skills_skills1`
    FOREIGN KEY (`SKILL_ID`)
    REFERENCES `pm`.`skills` (`SKILL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`developers_projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm`.`developers_projects` ;

CREATE TABLE IF NOT EXISTS `pm`.`developers_projects` (
  `DEVELOPER_ID` INT NOT NULL,
  `PROJECT_ID` INT NOT NULL,
  PRIMARY KEY (`DEVELOPER_ID`, `PROJECT_ID`),
  INDEX `fk_developers_has_projects_projects1_idx` (`PROJECT_ID` ASC),
  INDEX `fk_developers_has_projects_developers1_idx` (`DEVELOPER_ID` ASC),
  CONSTRAINT `fk_developers_has_projects_developers1`
    FOREIGN KEY (`DEVELOPER_ID`)
    REFERENCES `pm`.`developers` (`DEVELOPER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_developers_has_projects_projects1`
    FOREIGN KEY (`PROJECT_ID`)
    REFERENCES `pm`.`projects` (`PROJECT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`customers_projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm`.`customers_projects` ;

CREATE TABLE IF NOT EXISTS `pm`.`customers_projects` (
  `CUSTOMER_ID` INT NOT NULL,
  `PROJECT_ID` INT NOT NULL,
  PRIMARY KEY (`CUSTOMER_ID`, `PROJECT_ID`),
  INDEX `fk_customers_has_projects_projects1_idx` (`PROJECT_ID` ASC),
  INDEX `fk_customers_has_projects_customers1_idx` (`CUSTOMER_ID` ASC),
  CONSTRAINT `fk_customers_has_projects_customers1`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `pm`.`customers` (`CUSTOMER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customers_has_projects_projects1`
    FOREIGN KEY (`PROJECT_ID`)
    REFERENCES `pm`.`projects` (`PROJECT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`companies_projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm`.`companies_projects` ;

CREATE TABLE IF NOT EXISTS `pm`.`companies_projects` (
  `COMPANY_ID` INT NOT NULL,
  `PROJECT_ID` INT NOT NULL,
  PRIMARY KEY (`COMPANY_ID`, `PROJECT_ID`),
  INDEX `fk_companies_has_projects_projects1_idx` (`PROJECT_ID` ASC),
  INDEX `fk_companies_has_projects_companies1_idx` (`COMPANY_ID` ASC),
  CONSTRAINT `fk_companies_has_projects_companies1`
    FOREIGN KEY (`COMPANY_ID`)
    REFERENCES `pm`.`companies` (`COMPANY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_companies_has_projects_projects1`
    FOREIGN KEY (`PROJECT_ID`)
    REFERENCES `pm`.`projects` (`PROJECT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`companies_developers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm`.`companies_developers` ;

CREATE TABLE IF NOT EXISTS `pm`.`companies_developers` (
  `COMPANY_ID` INT NOT NULL,
  `DEVELOPER_ID` INT NOT NULL,
  PRIMARY KEY (`COMPANY_ID`, `DEVELOPER_ID`),
  INDEX `fk_companies_has_developers_developers1_idx` (`DEVELOPER_ID` ASC),
  INDEX `fk_companies_has_developers_companies1_idx` (`COMPANY_ID` ASC),
  CONSTRAINT `fk_companies_has_developers_companies1`
    FOREIGN KEY (`COMPANY_ID`)
    REFERENCES `pm`.`companies` (`COMPANY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_companies_has_developers_developers1`
    FOREIGN KEY (`DEVELOPER_ID`)
    REFERENCES `pm`.`developers` (`DEVELOPER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`companies_customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pm`.`companies_customers` ;

CREATE TABLE IF NOT EXISTS `pm`.`companies_customers` (
  `COMPANY_ID` INT NOT NULL,
  `CUSTOMER_ID` INT NOT NULL,
  PRIMARY KEY (`COMPANY_ID`, `CUSTOMER_ID`),
  INDEX `fk_companies_has_customers_customers1_idx` (`CUSTOMER_ID` ASC),
  INDEX `fk_companies_has_customers_companies1_idx` (`COMPANY_ID` ASC),
  CONSTRAINT `fk_companies_has_customers_companies1`
    FOREIGN KEY (`COMPANY_ID`)
    REFERENCES `pm`.`companies` (`COMPANY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_companies_has_customers_customers1`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `pm`.`customers` (`CUSTOMER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;